"use client";

import { useRef } from "react";
import moment from "moment";
import { useReactToPrint } from "react-to-print";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

export type MedicalReport = {
  agent?: string;
  chiefComplaint?: string;
  summary?: string;
  duration?: string;
  severity?: string;
  user?: string;
  symptoms?: string[];
  medicationsMentioned?: string[];
  recommendations?: string[];
};

type Props = {
  record: {
    sessionId: string;
    createdOn: string;
    selectedDoctor?: { specialist?: string };
    report?: MedicalReport;
  };
};

export default function ViewReportDialog({ record }: Props) {
  const reportRef = useRef<HTMLDivElement>(null);
  const r = record?.report || {};

  const handlePrint = useReactToPrint({
    contentRef: reportRef, // ✅ use contentRef, not content
    documentTitle: `MumWell-Medical-Report-${record.sessionId}`,
  });

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="link">View Report</Button>
      </DialogTrigger>

      <DialogContent className="max-w-6xl max-h-[90vh] bg-secondary overflow-y-auto rounded-xl border md:mt-24 mt-20 mb-1">
        <DialogHeader>
          <DialogTitle className="text-center text-3xl font-bold underline underline-offset-4">
            MumWell AI Medical Report
          </DialogTitle>
        </DialogHeader>

        <div
          ref={reportRef}
          className="p-6 space-y-6 bg-secondary rounded-lg shadow-sm"
        >
          {/* Header */}
          <div className="border-b pb-4">
            <h2 className="text-xl font-bold mb-3">Consultation Overview</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
              <p>
                <span className="font-semibold">Doctor:</span>{" "}
                {record?.selectedDoctor?.specialist || "N/A"}
              </p>
              <p>
                <span className="font-semibold">Date:</span>{" "}
                {moment(record.createdOn).format("MMMM Do YYYY, h:mm A")}
              </p>
              <p>
                <span className="font-semibold">Patient:</span>{" "}
                {r.user || "Anonymous"}
              </p>
            </div>
          </div>

          {/* Body Sections */}
          <CardSection title="Chief Complaint" value={r.chiefComplaint} />
          <CardSection title="Summary" value={r.summary} />
          <CardList title="Symptoms" list={r.symptoms} />
          <CardSection title="Duration" value={r.duration} />
          <CardSection title="Severity" value={r.severity} />
          <CardList
            title="Medications Mentioned"
            list={r.medicationsMentioned}
          />
          <CardList title="Recommendations" list={r.recommendations} />

          {/* Disclaimer */}
          <div className="mt-8 p-4 bg-f3f6fa border-l-4 border-orange-600 rounded-md shadow-sm">
            <h3 className="font-bold text-orange-700 mb-1">Disclaimer</h3>
            <p className="text-sm text-orange-700 leading-relaxed">
              This report was generated by an AI medical assistant. It does not
              replace professional medical diagnosis, treatment, or advice.
              Always consult a licensed healthcare provider for medical
              decisions.
            </p>
          </div>
        </div>

        {/* Print Button */}
        <div className="mt-6 flex justify-end mb-10">
          <Button onClick={handlePrint} className="bg-primary text-white">
            Print / Save PDF
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

/* ---------------- Reusable Components ---------------- */

function CardSection({ title, value }: { title: string; value?: string }) {
  if (!value) return null;
  return (
    <div className="p-4 border rounded-lg shadow-sm bg-destructive-foreground">
      <h3 className="font-bold text-lg mb-1 underline underline-offset-4">
        {title}
      </h3>
      <p className="text-muted-foreground leading-relaxed">{value}</p>
    </div>
  );
}

function CardList({ title, list }: { title: string; list?: string[] }) {
  if (!list || list.length === 0) return null;
  return (
    <div className="p-4 border rounded-lg shadow-sm bg-destructive-foreground">
      <h3 className="font-bold text-lg mb-1 underline underline-offset-4">
        {title}
      </h3>
      <ul className="list-disc ml-6 text-muted-foreground space-y-1">
        {list.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
    </div>
  );
}
